In [54]:
import pandas as pd
import numpy as np
import os

In [55]:
MentalHealthCSV = os.path.join('raw_data', 'LLCP2016.XPT')

mentalHealth_df = pd.read_sas(MentalHealthCSV)

#df = pd.read_sas('LLCP2016.XPT')



mentalHealth_df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_MAM5021,_RFPAP33,_RFPSA21,_RFBLDS3,_COL10YR,_HFOB3YR,_FS5YR,_FOBTFS,_CRCREC,_AIDTST3
0,1.0,1.0,b'01072016',b'01',b'07',b'2016',1100.0,b'2016000001',2.016000e+09,1.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1.0,1.0,b'01112016',b'01',b'11',b'2016',1100.0,b'2016000002',2.016000e+09,1.0,...,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,2.0
2,1.0,1.0,b'01062016',b'01',b'06',b'2016',1100.0,b'2016000003',2.016000e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,1.0,1.0,b'01082016',b'01',b'08',b'2016',1100.0,b'2016000004',2.016000e+09,1.0,...,NaN,NaN,1.0,2.0,1.0,2.0,NaN,2.0,1.0,9.0
4,1.0,1.0,b'01052016',b'01',b'05',b'2016',1100.0,b'2016000005',2.016000e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [56]:
mentalHealth_df.columns.values.tolist()

['_STATE',
 'FMONTH',
 'IDATE',
 'IMONTH',
 'IDAY',
 'IYEAR',
 'DISPCODE',
 'SEQNO',
 '_PSU',
 'CTELENM1',
 'PVTRESD1',
 'COLGHOUS',
 'STATERES',
 'CELLFON4',
 'LADULT',
 'NUMADULT',
 'NUMMEN',
 'NUMWOMEN',
 'CTELNUM1',
 'CELLFON5',
 'CADULT',
 'PVTRESD3',
 'CCLGHOUS',
 'CSTATE1',
 'LANDLINE',
 'HHADULT',
 'GENHLTH',
 'PHYSHLTH',
 'MENTHLTH',
 'POORHLTH',
 'HLTHPLN1',
 'PERSDOC2',
 'MEDCOST',
 'CHECKUP1',
 'EXERANY2',
 'SLEPTIM1',
 'CVDINFR4',
 'CVDCRHD4',
 'CVDSTRK3',
 'ASTHMA3',
 'ASTHNOW',
 'CHCSCNCR',
 'CHCOCNCR',
 'CHCCOPD1',
 'HAVARTH3',
 'ADDEPEV2',
 'CHCKIDNY',
 'DIABETE3',
 'DIABAGE2',
 'LASTDEN3',
 'RMVTETH3',
 'SEX',
 'MARITAL',
 'EDUCA',
 'RENTHOM1',
 'NUMHHOL2',
 'NUMPHON2',
 'CPDEMO1',
 'VETERAN3',
 'EMPLOY1',
 'CHILDREN',
 'INCOME2',
 'INTERNET',
 'WEIGHT2',
 'HEIGHT3',
 'PREGNANT',
 'DEAF',
 'BLIND',
 'DECIDE',
 'DIFFWALK',
 'DIFFDRES',
 'DIFFALON',
 'SMOKE100',
 'SMOKDAY2',
 'STOPSMK2',
 'LASTSMK2',
 'USENOW3',
 'ECIGARET',
 'ECIGNOW',
 'ALCDAY5',
 'AVEDRNK2',
 'DRNK3GE5',
 'MAXDRNKS',
 'FLUSHOT6',
 'FLSHTMY2',
 'PNEUVAC3',
 'TETANUS',
 'FALL12MN',
 'FALLINJ2',
 'SEATBELT',
 'DRNKDRI2',
 'HADMAM',
 'HOWLONG',
 'HADPAP2',
 'LASTPAP2',
 'HPVTEST',
 'HPLSTTST',
 'HADHYST2',
 'PCPSAAD2',
 'PCPSADI1',
 'PCPSARE1',
 'PSATEST1',
 'PSATIME',
 'PCPSARS1',
 'BLDSTOOL',
 'LSTBLDS3',
 'HADSIGM3',
 'HADSGCO1',
 'LASTSIG3',
 'HIVTST6',
 'HIVTSTD3',
 'HIVRISK4',
 'PDIABTST',
 'PREDIAB1',
 'INSULIN',
 'BLDSUGAR',
 'FEETCHK2',
 'DOCTDIAB',
 'CHKHEMO3',
 'FEETCHK',
 'EYEEXAM',
 'DIABEYE',
 'DIABEDU',
 'PAINACT2',
 'QLMENTL2',
 'QLSTRES2',
 'QLHLTH2',
 'MEDICARE',
 'HLTHCVR1',
 'DELAYMED',
 'DLYOTHER',
 'NOCOV121',
 'LSTCOVRG',
 'DRVISITS',
 'MEDSCOST',
 'CARERCVD',
 'MEDBILL1',
 'MEDADVIC',
 'UNDRSTND',
 'WRITTEN',
 'CAREGIV1',
 'CRGVREL1',
 'CRGVLNG1',
 'CRGVHRS1',
 'CRGVPRB2',
 'CRGVPERS',
 'CRGVHOUS',
 'CRGVMST2',
 'CRGVEXPT',
 'CIMEMLOS',
 'CDHOUSE',
 'CDASSIST',
 'CDHELP',
 'CDSOCIAL',
 'CDDISCUS',
 'SSBSUGR2',
 'SSBFRUT2',
 'CALRINFO',
 'MARIJANA',
 'USEMRJNA',
 'ASTHMAGE',
 'ASATTACK',
 'ASERVIST',
 'ASDRVIST',
 'ASRCHKUP',
 'ASACTLIM',
 'ASYMPTOM',
 'ASNOSLEP',
 'ASTHMED3',
 'ASINHALR',
 'IMFVPLAC',
 'HPVADVC2',
 'HPVADSHT',
 'SHINGLE2',
 'NUMBURN2',
 'CNCRDIFF',
 'CNCRAGE',
 'CNCRTYP1',
 'CSRVTRT1',
 'CSRVDOC1',
 'CSRVSUM',
 'CSRVRTRN',
 'CSRVINST',
 'CSRVINSR',
 'CSRVDEIN',
 'CSRVCLIN',
 'CSRVPAIN',
 'CSRVCTL1',
 'PROFEXAM',
 'LENGEXAM',
 'PCPSADE1',
 'PCDMDECN',
 'SXORIENT',
 'TRNSGNDR',
 'RCSGENDR',
 'RCSRLTN2',
 'CASTHDX2',
 'CASTHNO2',
 'EMTSUPRT',
 'LSATISFY',
 'QLACTLM2',
 'USEEQUIP',
 'QSTVER',
 'QSTLANG',
 'MSCODE',
 '_STSTR',
 '_STRWT',
 '_RAWRAKE',
 '_WT2RAKE',
 '_CHISPNC',
 '_CRACE1',
 '_CPRACE',
 '_CLLCPWT',
 '_DUALUSE',
 '_DUALCOR',
 '_LLCPWT2',
 '_LLCPWT',
 '_RFHLTH',
 '_PHYS14D',
 '_MENT14D',
 '_HCVU651',
 '_TOTINDA',
 '_MICHD',
 '_LTASTH1',
 '_CASTHM1',
 '_ASTHMS1',
 '_DRDXAR1',
 '_EXTETH2',
 '_ALTETH2',
 '_DENVST2',
 '_PRACE1',
 '_MRACE1',
 '_HISPANC',
 '_RACE',
 '_RACEG21',
 '_RACEGR3',
 '_RACE_G1',
 '_AGEG5YR',
 '_AGE65YR',
 '_AGE80',
 '_AGE_G',
 'HTIN4',
 'HTM4',
 'WTKG3',
 '_BMI5',
 '_BMI5CAT',
 '_RFBMI5',
 '_CHLDCNT',
 '_EDUCAG',
 '_INCOMG',
 '_SMOKER3',
 '_RFSMOK3',
 '_ECIGSTS',
 '_CURECIG',
 'DRNKANY5',
 'DROCDY3_',
 '_RFBING5',
 '_DRNKWEK',
 '_RFDRHV5',
 '_FLSHOT6',
 '_PNEUMO2',
 '_RFSEAT2',
 '_RFSEAT3',
 '_DRNKDRV',
 '_RFMAM2Y',
 '_MAM5021',
 '_RFPAP33',
 '_RFPSA21',
 '_RFBLDS3',
 '_COL10YR',
 '_HFOB3YR',
 '_FS5YR',
 '_FOBTFS',
 '_CRCREC',
 '_AIDTST3']

In [57]:
# To pull needed columns only 


reduced_mental_health_data = mentalHealth_df.loc[:, ['IDATE','_STATE', 'SEX', '_AGEG5YR', '_PRACE1', 'EMPLOY1', 'MSCODE',
                                        'MENTHLTH',
                                        '_RFHLTH',
                                        '_HCVU651', 'SLEPTIM1','CVDINFR4', 
                                        'CVDCRHD4', 'CVDSTRK3', 'ASTHNOW', 'CHCSCNCR', 'CHCOCNCR',
                                        'CHCCOPD1',
                                        '_DRDXAR1','ADDEPEV2', 'CHCKIDNY', 'DIABETE3', 
                                        'PREGNANT', 'QLMENTL2', 'QLSTRES2', '_RFSMOK3', 
                                        '_RFDRHV5', '_TOTINDA', '_INCOMG', '_BMI5CAT', 
                                        'EMTSUPRT', 'LSATISFY']]

#New added:
#_RFHLTH',
  # '_HCVU651', '_DRDXAR1'
    
#    'QLMENTL2'
#'QLSTRES2', '_RFSMOK3', '_TOTINDA' (Phyicall Activity), '_INCOMG'

reduced_mental_health_data.head()

,IDATE,_STATE,SEX,_AGEG5YR,_PRACE1,EMPLOY1,MSCODE,MENTHLTH,_RFHLTH,_HCVU651,...,PREGNANT,QLMENTL2,QLSTRES2,_RFSMOK3,_RFDRHV5,_TOTINDA,_INCOMG,_BMI5CAT,EMTSUPRT,LSATISFY
0,b'01072016',1.0,1.0,5.0,1.0,1.0,3.0,88.0,1.0,1.0,...,NaN,NaN,NaN,1.0,1.0,1.0,3.0,2.0,NaN,NaN
1,b'01112016',1.0,2.0,8.0,1.0,5.0,1.0,88.0,1.0,1.0,...,NaN,NaN,NaN,1.0,1.0,1.0,5.0,3.0,NaN,NaN
2,b'01062016',1.0,2.0,13.0,1.0,7.0,2.0,1.0,1.0,9.0,...,NaN,NaN,NaN,2.0,1.0,1.0,5.0,2.0,NaN,NaN
3,b'01082016',1.0,1.0,11.0,1.0,7.0,1.0,88.0,1.0,9.0,...,NaN,NaN,NaN,1.0,1.0,1.0,5.0,3.0,NaN,NaN
4,b'01052016',1.0,1.0,1.0,1.0,1.0,3.0,3.0,2.0,1.0,...,NaN,NaN,NaN,1.0,1.0,1.0,9.0,2.0,NaN,NaN

In [58]:
reduced_mental_health_data["IDATE"] = reduced_mental_health_data["IDATE"].str.decode("utf-8")
reduced_mental_health_data["SEX"] = reduced_mental_health_data["SEX"].replace({1.0:"M",2.0:"F", 9: "NA", None:"NA"})


reduced_mental_health_data["_AGEG5YR"]=reduced_mental_health_data["_AGEG5YR"].replace({1.0:"18-24",2.0:"25-29",3.0:"30-34",4.0:"35-39",5.0:"40-44",
                                                  6.0:"45-49",7.0:"50-54",8.0:"55-59",9.0:"60-64",10.0:"65-69",
                                                  11.0:"70-74",12.0:"75-79",13.0:"80+",14.0:"NA",None:"NA"})
reduced_mental_health_data["EMPLOY1"]=reduced_mental_health_data["EMPLOY1"].replace({1.0:"Employed", 2.0:"Self-Employed", 3.0:"Out of work",
                                               4.0:"Out of work", 5.0:"Homemaker", 6.0:"Student",
                                               7.0:"Retired", 8.0:"Unable to work", 9.0:"NA",None:"NA"})

In [59]:
reduced_mental_health_data["_PRACE1"]=reduced_mental_health_data["_PRACE1"].replace({1.0:"White",2.0:"Black or African American",3.0:"Asian",
                                               4.0:"Native Hawaiian or Other Pacific Islander",
                                               5.0:"American Indian, Alaska Native",6.0:"Other",
                                               7.0:"NA", 8.0:"Multiracial",9.0:"NA"})
reduced_mental_health_data["MENTHLTH"]=reduced_mental_health_data["MENTHLTH"].replace({88:0, 77:0, 99:0, None:0})
reduced_mental_health_data["_RFHLTH"]=reduced_mental_health_data["_RFHLTH"].replace({1:"Good",2:"Poor",9:"NA",None:"NA"})
#reduced_mental_health_data["HLTHPLN1"]=reduced_mental_health_data["HLTHPLN1"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})

In [60]:
#Chronic Health Disease 
reduced_mental_health_data["CVDINFR4"]=reduced_mental_health_data["CVDINFR4"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["CVDCRHD4"]=reduced_mental_health_data["CVDCRHD4"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["CVDSTRK3"]=reduced_mental_health_data["CVDSTRK3"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["ASTHNOW"]=reduced_mental_health_data["ASTHNOW"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["CHCSCNCR"]=reduced_mental_health_data["CHCSCNCR"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["CHCOCNCR"]=reduced_mental_health_data["CHCOCNCR"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["CHCCOPD1"]=reduced_mental_health_data["CHCCOPD1"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["_DRDXAR1"]=reduced_mental_health_data["_DRDXAR1"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})

In [61]:
reduced_mental_health_data["ADDEPEV2"]=reduced_mental_health_data["ADDEPEV2"].replace({1:"Y", 2:"N", 7:"NA", 9:"NA",None:"NA"})

reduced_mental_health_data["CHCKIDNY"]=reduced_mental_health_data["CHCKIDNY"].replace({1:"Y", 2:"N", 7:0, 9:0,None:0})
reduced_mental_health_data["DIABETE3"]=reduced_mental_health_data["DIABETE3"].replace({1:"Y", 2:"N", 3:"N", 4:"N", 7:0, 9:0,None:0})

In [62]:
reduced_mental_health_data["PREGNANT"]=reduced_mental_health_data["PREGNANT"].replace({1:"Y", 2:"N", 7:"NA", 9:"NA",None:"NA"})
reduced_mental_health_data["_BMI5CAT"]=reduced_mental_health_data["_BMI5CAT"].replace({4:"Obese",3:"Overweight",2:"Normal Weight",1:"Underweight",None:"NA"})
reduced_mental_health_data["QLMENTL2"]=reduced_mental_health_data["QLMENTL2"].replace({88:0, 77: 0, 99: 0, None: 0})
reduced_mental_health_data["_TOTINDA"]=reduced_mental_health_data["_TOTINDA"].replace({2:"N",1:"Y",9:"NA",None:"NA"})
reduced_mental_health_data["QLSTRES2"]=reduced_mental_health_data["QLSTRES2"].replace({88:0, 77:0, 99:0, None:0})

In [63]:
reduced_mental_health_data["_RFSMOK3"]=reduced_mental_health_data["_RFSMOK3"].replace({1:"Non-Smoker",2:"Smoker",9.0:"NA",None:"NA"})
                                                   #7.0:0,9.0:0,None:0})

reduced_mental_health_data["_RFDRHV5"]=reduced_mental_health_data["_RFDRHV5"].replace({1:"Non-Alcoholic",2:"Alcoholic",9.0:"NA",None:"NA"})

reduced_mental_health_data["MSCODE"]=reduced_mental_health_data["MSCODE"].replace({5:"Rural",3:"Urban",2:"Urban",1:"Urban",None:"Rural"})

In [64]:
reduced_mental_health_data["LSATISFY"]=reduced_mental_health_data["LSATISFY"].replace({1: "Satisfied", 2: "Satisfied", 3: "Not-Satisfied", 4: "Not-Satisfied", 7: "NA", 9:"NA",None:"NA"})
reduced_mental_health_data["EMTSUPRT"]=reduced_mental_health_data["EMTSUPRT"].replace({7:"NA", 9:"NA", None:"NA"})

reduced_mental_health_data["_INCOMG"]=reduced_mental_health_data["_INCOMG"].replace({1:"<15000", 2:"15000-<25000",
                                                 3:"25000-<35000", 4:"35000-<50000",
                                                 5:"50000+",9:"NA",None:"NA"})

In [65]:
reduced_mental_health_data.head()

,IDATE,_STATE,SEX,_AGEG5YR,_PRACE1,EMPLOY1,MSCODE,MENTHLTH,_RFHLTH,_HCVU651,...,PREGNANT,QLMENTL2,QLSTRES2,_RFSMOK3,_RFDRHV5,_TOTINDA,_INCOMG,_BMI5CAT,EMTSUPRT,LSATISFY
0,01072016,1.0,M,40-44,White,Employed,Urban,0.0,Good,1.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,25000-<35000,Normal Weight,NA,NA
1,01112016,1.0,F,55-59,White,Homemaker,Urban,0.0,Good,1.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA
2,01062016,1.0,F,80+,White,Retired,Urban,1.0,Good,9.0,...,NA,0.0,0.0,Smoker,Non-Alcoholic,Y,50000+,Normal Weight,NA,NA
3,01082016,1.0,M,70-74,White,Retired,Urban,0.0,Good,9.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA
4,01052016,1.0,M,18-24,White,Employed,Urban,3.0,Poor,1.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,NA,Normal Weight,NA,NA

In [66]:
# Converting State numbers into State Codes

reduced_mental_health_data = reduced_mental_health_data.rename(columns={"_STATE":"fips"})


outputfilepath=os.path.join("raw_data","fipstostate.csv")
FIP_State=pd.read_csv(outputfilepath)
FIP_State.head()

   fips state_abbr
0     1         AL
1     2         AK
2     4         AZ
3     5         AR
4     6         CA

In [67]:
reduced_mental_health_data.head()

,IDATE,fips,SEX,_AGEG5YR,_PRACE1,EMPLOY1,MSCODE,MENTHLTH,_RFHLTH,_HCVU651,...,PREGNANT,QLMENTL2,QLSTRES2,_RFSMOK3,_RFDRHV5,_TOTINDA,_INCOMG,_BMI5CAT,EMTSUPRT,LSATISFY
0,01072016,1.0,M,40-44,White,Employed,Urban,0.0,Good,1.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,25000-<35000,Normal Weight,NA,NA
1,01112016,1.0,F,55-59,White,Homemaker,Urban,0.0,Good,1.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA
2,01062016,1.0,F,80+,White,Retired,Urban,1.0,Good,9.0,...,NA,0.0,0.0,Smoker,Non-Alcoholic,Y,50000+,Normal Weight,NA,NA
3,01082016,1.0,M,70-74,White,Retired,Urban,0.0,Good,9.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA
4,01052016,1.0,M,18-24,White,Employed,Urban,3.0,Poor,1.0,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,Y,NA,Normal Weight,NA,NA

In [68]:
reduced_mental_health_data = reduced_mental_health_data.merge(FIP_State,on="fips")
reduced_mental_health_data.drop("fips",axis=1,inplace=True)
reduced_mental_health_data["Chronic_Disease"]=""

reduced_mental_health_data.head()

,IDATE,SEX,_AGEG5YR,_PRACE1,EMPLOY1,MSCODE,MENTHLTH,_RFHLTH,_HCVU651,SLEPTIM1,...,QLSTRES2,_RFSMOK3,_RFDRHV5,_TOTINDA,_INCOMG,_BMI5CAT,EMTSUPRT,LSATISFY,state_abbr,Chronic_Disease
0,01072016,M,40-44,White,Employed,Urban,0.0,Good,1.0,5.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,25000-<35000,Normal Weight,NA,NA,AL,
1,01112016,F,55-59,White,Homemaker,Urban,0.0,Good,1.0,6.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,
2,01062016,F,80+,White,Retired,Urban,1.0,Good,9.0,9.0,...,0.0,Smoker,Non-Alcoholic,Y,50000+,Normal Weight,NA,NA,AL,
3,01082016,M,70-74,White,Retired,Urban,0.0,Good,9.0,7.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,
4,01052016,M,18-24,White,Employed,Urban,3.0,Poor,1.0,6.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,NA,Normal Weight,NA,NA,AL,

In [69]:
# Function to Aggregating Chronic Disease 

for index, row in reduced_mental_health_data.iterrows():
    chron_dep=0
    if row["CVDINFR4"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["CVDCRHD4"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["CVDSTRK3"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["ASTHNOW"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["CHCSCNCR"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["CHCOCNCR"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["CHCCOPD1"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["_DRDXAR1"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["CHCKIDNY"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    if row["DIABETE3"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    reduced_mental_health_data.set_value(index, "Chronic_Disease",chron_dep)


reduced_mental_health_data.drop(["CVDINFR4","CVDCRHD4","CVDSTRK3","ASTHNOW","CHCSCNCR",
          "CHCOCNCR","CHCCOPD1","_DRDXAR1","CHCKIDNY","DIABETE3"],axis=1,inplace=True)

reduced_mental_health_data.head()

,IDATE,SEX,_AGEG5YR,_PRACE1,EMPLOY1,MSCODE,MENTHLTH,_RFHLTH,_HCVU651,SLEPTIM1,...,QLSTRES2,_RFSMOK3,_RFDRHV5,_TOTINDA,_INCOMG,_BMI5CAT,EMTSUPRT,LSATISFY,state_abbr,Chronic_Disease
0,01072016,M,40-44,White,Employed,Urban,0.0,Good,1.0,5.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,25000-<35000,Normal Weight,NA,NA,AL,0
1,01112016,F,55-59,White,Homemaker,Urban,0.0,Good,1.0,6.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,0
2,01062016,F,80+,White,Retired,Urban,1.0,Good,9.0,9.0,...,0.0,Smoker,Non-Alcoholic,Y,50000+,Normal Weight,NA,NA,AL,3
3,01082016,M,70-74,White,Retired,Urban,0.0,Good,9.0,7.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,3
4,01052016,M,18-24,White,Employed,Urban,3.0,Poor,1.0,6.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,NA,Normal Weight,NA,NA,AL,0

In [70]:
reduced_mental_health_data = reduced_mental_health_data.rename(columns={"_AGEG5YR":"Age_Range",
                                  "state_abbr":"State","SEX":"Gender",
                                  "MSCODE":"MetroStatusCode",
                                    "EMPLOY1":"Employment_Status",
                                  "MENTHLTH":"Mental_Health_Factor", 
                                  "_RFHLTH":"General_Health",
                                    "_HCVU651":"Health_Coverage",
                                  "ADDEPEV2":"Chronic_Depression",
                                  "QLACTLM2":"DISABLED",
                                  "SLEPTIM1":"Sleep_Hours",
                                    "QLMENTL2":"Depressed_Days",
                                  "QLSTRES2":"Stress_Days", 
                                  "_RFSMOK3":"Smoke_Frequency",
                                    "_RFDRHV5":"Alcohol_Frequency",
                                  "PREGNANT":"Pregnant",
                                    "IDATE":"Date","_PRACE1":"Race",
                                  "_TOTINDA":"Physical_Activity",
                                  "_INCOMG":"Income","_BMI5CAT":"BMI",
                                 "EMTSUPRT":"EmotionalSupport_Availability",
                                  "LSATISFY":"LifeSatisfaction_Level",
                                  

})

reduced_mental_health_data.head()

,Date,Gender,Age_Range,Race,Employment_Status,MetroStatusCode,Mental_Health_Factor,General_Health,Health_Coverage,Sleep_Hours,...,Stress_Days,Smoke_Frequency,Alcohol_Frequency,Physical_Activity,Income,BMI,EmotionalSupport_Availability,LifeSatisfaction_Level,State,Chronic_Disease
0,01072016,M,40-44,White,Employed,Urban,0.0,Good,1.0,5.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,25000-<35000,Normal Weight,NA,NA,AL,0
1,01112016,F,55-59,White,Homemaker,Urban,0.0,Good,1.0,6.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,0
2,01062016,F,80+,White,Retired,Urban,1.0,Good,9.0,9.0,...,0.0,Smoker,Non-Alcoholic,Y,50000+,Normal Weight,NA,NA,AL,3
3,01082016,M,70-74,White,Retired,Urban,0.0,Good,9.0,7.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,3
4,01052016,M,18-24,White,Employed,Urban,3.0,Poor,1.0,6.0,...,0.0,Non-Smoker,Non-Alcoholic,Y,NA,Normal Weight,NA,NA,AL,0

In [71]:
outputfilepath=os.path.join("raw_data","output", "MentalHealth_2016.csv")

reduced_mental_health_data.to_csv(outputfilepath,index=False)

In [72]:
reduced_mental_health_data.columns.values.tolist()

['Date',
 'Gender',
 'Age_Range',
 'Race',
 'Employment_Status',
 'MetroStatusCode',
 'Mental_Health_Factor',
 'General_Health',
 'Health_Coverage',
 'Sleep_Hours',
 'Chronic_Depression',
 'Pregnant',
 'Depressed_Days',
 'Stress_Days',
 'Smoke_Frequency',
 'Alcohol_Frequency',
 'Physical_Activity',
 'Income',
 'BMI',
 'EmotionalSupport_Availability',
 'LifeSatisfaction_Level',
 'State',
 'Chronic_Disease']

In [ ]:
#outputfilepath=os.path.join("raw_data","output", "BRFSS_2016.csv")

#brfss_data_2016 = pd.read_csv(outputfilepath) #TODO: Set low_memory = false 
#brfss_data_2016.head()

In [73]:
# A funtion to find a weighted variable based on various factors as the Mental Health Value
def CalculatedVariable(DF):
    
    # For each record in the dat
    for index,row in DF.iterrows():
        
        # Intializing the variables
        CalcVar=0
        TotalWght=0
        
        # Priority 1
        
        # For General Health 
        if row["General_Health"]=="Poor":
            CalcVar+=10
        else:
            CalcVar+=0
        
        # For Smokers
        if row["Smoke_Frequency"]=="Smoker":
            CalcVar+=10
        else:
            CalcVar+=0
        
        # For Alcoholics
        if row["Alcohol_Frequency"]=="Alcoholic":
            CalcVar+=10
        else:
            CalcVar+=0

        # For Sleeping disorders
        if row["Sleep_Hours"]<5 and row["Sleep_Hours"]>10:
            CalcVar+=10
        else:
            CalcVar+=0
        
        # For Obesity, Overweight and Underweight
        if row["BMI"]=="Obese":
            CalcVar+=10
        elif row["BMI"]=="Overweight":
            CalcVar+=8
        elif row["BMI"]=="Underweight":
            CalcVar+=8
        else:
            CalcVar+=0

        # For Physical Activity
        if row["Physical_Activity"]=="N":
            CalcVar+=10
        else:
            CalcVar+=0

        # For Chronic Disease
        # As there is already a existing value in the score of 10 adding that value to the Calculated Variable
        CalcVar+=row["Chronic_Disease"]

        # For Pregnancy
        if row["Pregnant"]=="Y":
            CalcVar+=10
        else:
            CalcVar+=0
    
    
        # Priority 2
        # For Income
        if row["Income"]=="<15000":
            CalcVar+=5
        elif row["Income"]=="15000-<25000":
            CalcVar+=4
        elif row["Income"]=="25000-<35000":
            CalcVar+=3
        elif row["Income"]=="35000-<50000":
            CalcVar+=2
        elif row["Income"]=="50000+":
            CalcVar+=1

        # Priority 3
        # For Emotional Support Availability
        if row["EmotionalSupport_Availability"]==1:
            CalcVar+=0.5
        elif row["EmotionalSupport_Availability"]==2:
            CalcVar+=1
        elif row["EmotionalSupport_Availability"]==3:
            CalcVar+=1.5
        elif row["EmotionalSupport_Availability"]==4:
            CalcVar+=2
        elif row["EmotionalSupport_Availability"]==5:
            CalcVar+=2.5
        # For Life Satisfaction Level
        if row["LifeSatisfaction_Level"]=="Not-Satisfied":
            CalcVar+=2.5
        else:
            CalcVar+=0
       
        # If the person has reported Chronic Depression
        if row["Chronic_Depression"]=="Y":
            chronic_dep=10
            # Converting the stress days(1-30) to a score of 10
            stress = row["Stress_Days"]*(1/3)
             # Converting the depressed days(1-30) to a score of 10
            depress=row["Depressed_Days"]*(1/3)
        else:
            # Converting the stress days(1-30) to a score of 10
            stress=row["Stress_Days"]*(1/3)
            # Converting the depressed days(1-30) to a score of 10
            depress=row["Depressed_Days"]*(1/3)
            chronic_dep=1
            
        # Calculating the average mental factor value
        avg_depr=(stress+depress+chronic_dep)*(2/3)
        
        # Checking if male or female and based on that converting the score to 100
        if row["Gender"]=="M":
            TotalWght=(CalcVar+avg_depr)*100/100
        else:
            TotalWght=(CalcVar+avg_depr)*100/110
    
        DF.set_value(index,"Calc_MentalHealth_Value",round(TotalWght,2))

In [74]:
#To do ensure to add column on Mental Health illness and then finalize the csv file for 2016 

reduced_mental_health_data["Calc_MentalHealth_Value"] = ""

CalculatedVariable(reduced_mental_health_data)

reduced_mental_health_data.head()

,Date,Gender,Age_Range,Race,Employment_Status,MetroStatusCode,Mental_Health_Factor,General_Health,Health_Coverage,Sleep_Hours,...,Smoke_Frequency,Alcohol_Frequency,Physical_Activity,Income,BMI,EmotionalSupport_Availability,LifeSatisfaction_Level,State,Chronic_Disease,Calc_MentalHealth_Value
0,01072016,M,40-44,White,Employed,Urban,0.0,Good,1.0,5.0,...,Non-Smoker,Non-Alcoholic,Y,25000-<35000,Normal Weight,NA,NA,AL,0,3.67
1,01112016,F,55-59,White,Homemaker,Urban,0.0,Good,1.0,6.0,...,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,0,14.24
2,01062016,F,80+,White,Retired,Urban,1.0,Good,9.0,9.0,...,Smoker,Non-Alcoholic,Y,50000+,Normal Weight,NA,NA,AL,3,13.33
3,01082016,M,70-74,White,Retired,Urban,0.0,Good,9.0,7.0,...,Non-Smoker,Non-Alcoholic,Y,50000+,Overweight,NA,NA,AL,3,12.67
4,01052016,M,18-24,White,Employed,Urban,3.0,Poor,1.0,6.0,...,Non-Smoker,Non-Alcoholic,Y,NA,Normal Weight,NA,NA,AL,0,10.67

In [75]:
# Output the cleansed data file into an output file 

outputfilepath=os.path.join("raw_data","output", "MentalHealth_2016.csv")

reduced_mental_health_data.to_csv(outputfilepath,index=False)

In [77]:
print (reduced_mental_health_data.apply(pd.Series.nunique))

print (reduced_mental_health_data.Gender.unique())

print (reduced_mental_health_data.Calc_MentalHealth_Value.unique())

Date                              419
Gender                              3
Age_Range                          14
Race                               10
Employment_Status                   8
MetroStatusCode                     2
Mental_Health_Factor               31
General_Health                      3
Health_Coverage                     3
Sleep_Hours                        26
Chronic_Depression                  3
Pregnant                            3
Depressed_Days                     29
Stress_Days                        28
Smoke_Frequency                     3
Alcohol_Frequency                   3
Physical_Activity                   3
Income                              6
BMI                                 5
EmotionalSupport_Availability       6
LifeSatisfaction_Level              3
State                              53
Chronic_Disease                    11
Calc_MentalHealth_Value          1610
dtype: int64
['M' 'F' 'NA']
[3.67 14.24 13.33 ..., 35.5 67.67 68.67]

In [ ]:
#Gender across mental Health Illness across Gender 

import pandas as pd
import matplotlib.pyplot as plt
from pandas.tools.plotting import table

# sample data
raw_data = {'officer_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
        'jan_arrests': [4, 24, 31, 2, 3],
        'feb_arrests': [25, 94, 57, 62, 70],
        'march_arrests': [5, 43, 23, 23, 51]}
df = pd.DataFrame(raw_data, columns = ['officer_name', 'jan_arrests', 'feb_arrests', 'march_arrests'])
df['total_arrests'] = df['jan_arrests'] + df['feb_arrests'] + df['march_arrests']

plt.figure(figsize=(16,8))
# plot chart
ax1 = plt.subplot(121, aspect='equal')
df.plot(kind='pie', y = 'total_arrests', ax=ax1, autopct='%1.1f%%', 
 startangle=90, shadow=False, labels=df['officer_name'], legend = False, fontsize=14)

# plot table
ax2 = plt.subplot(122)
plt.axis('off')
tbl = table(ax2, df, loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(14)
plt.show()

In [ ]:
#To do: Horizontal Bar chart for Mental Health Illness vs Employment 

#To do Pie chart of mental Health ilnesss vs Gender

In [ ]:
#TODO: Rename the COlumns based on sematic names 
#  ASTHMA3 since asks for prior conditions we just need ASTHNOW

#Then pull appropraiet column and store as XPT file and then upload it for 2016 under raw_data folder 

#TO - Write Function for 
#    1) Parsing Date Recorded 
#    2) Employment Status 
#    3) "MENTHLTH": "Mental_Health_Factor" - Number of Days Mental Health Issue - Interpret: a) 1-30 days (can be made into a decimal factor ). b) Interpret  88 as 0 days or 0 factor. c) Others as NaN (N/A)
#    4) "POORHLTH": Poor Health Factor - Interpret Similar to (3)   - The field indicates no. of days did poor physical or mental health keep you from doing your usual activities, such as self-care, work, or recreation
#    5) "HLTHPLN1" : "Health_Coverage" - Health Coverege - Interpret: a) 1 (Yes) b) 2 (No) c) 7 & 9  (NaN)
#    6) "SLEPTIM1" : "Sleep_Hours" - On average, how many hours of sleep do you get in a 24-hour period - Interpret a) 1-24 (same as original field values) , b) 77, 99, BLANK as (Nan)
#    7) "CVDINFR4" : "Chronic_HeartAttack" - Ever diagnosed with heart attack - Interpret as a) 1 (yes) b) 2 (no) c) 7,9,BLANK (NaN)
#    8) "CVDCRHD4" : "Chronic_CoronaryHeartDisease" - Interpret similar to (7) above  
#    9) "CVDSTRK3" : "Chronic_Stroke" - Interpret similar to (7) above 
#   10) "ASTHNOW"  : "Chronic_Asthma" - Interpret similar to (7) above 
#   11) "CHCSCNCR" : "Chronic_SkinCancer" - Interpret similar to (7) above
#   12) "CHCOCNCR" : "Chronic_OtherCancer" - Interpret similar to (7) above
#   13) "CHCCOPD1" : "Chronic_Pulmonary", - Interpret similar to (7) above
#   14) "HAVARTH3" : "Chronic_Arthritis", - Interpret similar to (7) above
#   15) "ADDEPEV2" : "Chronic_Depression", - Interpret similar to (7) above
#   16) "CHCKIDNY" : "Chronic_KidneyDisease", - Interpret similar to (7) above
#   17) "DIABETE3" : "Chronic_Diabetes", - Interpret similar to (7) above
#   18) "PREGNANT" : "Pregnant" - Interpret similar to (7) above 
#   19) "DECIDE"   : "Difficulty_ConcentrateMemoryDecision" - Interpret similar to (7) above
#   20) 'DIFFALON' : "Difficulty_ErrandsAlone",  - Interpret similar to (7) above
#   21) 'SMOKDAY2' : "Smoke_Frequency", Interpret as a) 1 - (Every Day) b) 2 - (Some Days) c) 3 - (None) d) 7,9, BLANK - (NaN)
#   22) "ALCDAY5"  : "Alcohol_Frequency",  Interpret a) 1 X Y - XY can be 00 to 07 indicate number of days per week they drink alcohol -> (1/7 or n/7 decimal factor) b) 2 A B - A B indicates no. of days ina month where alcohol consumed -> (1/30 or n/30 decimal factor) c) 777, 888, 999, BLANk -> (Nan) 
#   23) "MARIJANA" : "Marijuana_Usage", Interpret a) 1-30 - No. days used per month (1/30 or n/30 decimal factor) b) 88 - 0 Days -> (0 usage) c) 77,99, BLANK -> (NaN)
#   24) "EMTSUPRT" : "EmotionalSupport_Availability" - Interpret a) 1 - (Always) b) 2 - (Usually) c) 3 - (Sometimes) d) 4 - (Rarely) e) 5 - (Never) f) 7,9, BLANK - (NaN)
#   25) "LSATISFY" : "LifeSatisfaction_Level" - Interpret as a) 1 - (Very Satisfied) b) 2 (Satisfied) c) 3 (Dissatisfied) d) 4 (Very Dissatisfied) e) 7,9, BLANK - (NaN)
#   26) "SEX"      : "Gender" - Interpret as a) 1 - (Male)  b) 2 - (Female)  c) 9 - (NaN)
#   27) "_STATE"   : "State" - Interpret State based on Number to State Mapping
#   28) "_AGEG5YR" : "Age_Range" - Interpret based on Age Range Buckets (See below) 
#   29) "_PRACE1"  : "Race" - Interept based on Race Mappings 
#   30) "MSCODE"   : "MetroStatusCode" - Interpret a) 1, 2, 3 -> (Urban)  b) 5 as (Rural) c)  Other - (NaN)

# Age Buckets:  Interpret: 
# 1)   1  - (18-24)  Respondents with reported age between 18 and 24 years (18 <= AGE <= 24)
# 2)   2  - (25-29) Respondents with reported age between 25 and 29 years (25 <= AGE <= 29)
# 3)   3  - (30-34) Respondents with reported age between 30 and 34 years (30 <= AGE <= 34)
# 4)   4  - (35-39) Respondents with reported age between 35 and 39 years (35 <= AGE <= 39)
# 5)   5  - (40-44) Respondents with reported age between 40 and 44 years (40 <= AGE <= 44)
# 6)   6  - (45-49) Respondents with reported age between 45 and 49 years (45 <= AGE <= 49)
# 7)   7  - (50-54) Respondents with reported age between 50 and 54 years (50 <= AGE <= 54)
# 8)   8  - (55-59) Respondents with reported age between 55 and 59 years (55 <= AGE <= 59)
# 9)   9  - (60-64) Respondents with reported age between 60 and 64 years (60 <= AGE <= 64)
# 10) 10  - (65-69) Respondents with reported age between 65 and 69 years (65 <= AGE <= 69)
# 11) 11  - (70-74) Respondents with reported age between 70 and 74 years (70 <= AGE <= 74)
# 12) 12  - (75-79) Respondents with reported age between 75 and 79 years (75 <= AGE <= 79)
# 13) 13  - (80 or older) Respondents with reported age between 80 and 99 years (80 <= AGE <= 99)
# 14) 14  - (NaN) Don’t know/ Respondents who reported they didn ́t know, were not sure, refused to report or Refused/ Missing had missing responses for their age.


#Interpret Employee Status status as: 
# a) 1 (Employed)
# b) 2 (Self-employed)
# c) 3 (Not Employed >= 1 year)
# d) 4 (Not Employed < 1 year) 
# e) 5 (Homemaker)
# f) 6 (Student)
# g) 7 (Retired)
# h) 8 (Not Employed)
# i) 9,10 (NaN)

#take out: POORHLTH	HLTHPLN1 'HAVARTH3' DECIDE', 'DIFFALON', 'SMOKDAY2', 'ALCDAY5', 'MARIJANA',

In [ ]:
# Find number of records present for the filtered columns in 2016 Data
print (len(reduced_mental_health_data.index))

In [ ]:
# Find unique values n each column - Then count them 

reduced_mental_health_data.apply(pd.Series.nunique)


# Write info into a CSV file if possible 

#Compare unique values again in each column and count them to see see if there is any data loss

In [82]:
print (reduced_mental_health_data.Gender.unique())

print (reduced_mental_health_data.Gender.count())

#df_filtered = df[df['column'] == value]
#test_df = pd.DataFrame()
#test_df = test_df.fillna(0) # with 0s rather than NaNs

#test_df = [(reduced_mental_health_data["Calc_MentalHealthValue"] > 40) & (reduced_mental_health_data["Race"])]
#test_pd = pd.DataFrame(test_df)

test_df = reduced_mental_health_data[reduced_mental_health_data['Calc_MentalHealthValue'] >= 40].groupby('Race').count()


Ketapril_pd = pd.DataFrame (clinical_ForKetapril)



test_pd.head()

['M' 'F' 'NA']
482451

KeyError: 'Calc_MentalHealthValue'

In [ ]:
# Write info into a CSV file if possible 

#reduced_mental_health_data.to_csv('MentalHealth2016.csv')

#Compare unique values again in each column and count them to see see if there is any data loss 

#read_csv to find un

#mental_health_csv_data.apply(pd.Series.nunique)

In [ ]:
#df2 = pd.read_csv('MentalHealth2016.csv')

#df2.head()

In [ ]:
#df2.apply(pd.Series.nunique)